{ config, lib, pkgs, ... }:

let
  cfg = config.services.gssproxy;

  # gssproxy.conf is an INI-like file: sections such as "[gssproxy]" or
  # "[service/nfs-server]", with indented "key = value" entries. Some keys
  # (notably cred_store) may legitimately appear multiple times, so list
  # values are rendered as one line per element.
  renderValue = v:
    if v == true then "yes"
    else if v == false then "no"
    else if builtins.isInt v then toString v
    else toString v;

  renderKV = key: value:
    if builtins.isList value
    then lib.concatMapStringsSep "\n" (item: "  ${key} = ${renderValue item}") value
    else "  ${key} = ${renderValue value}";

  renderSection = name: attrs:
    "[${name}]\n"
    + lib.concatStringsSep "\n" (lib.mapAttrsToList renderKV attrs)
    + "\n";

  settingsToConf = settings:
    lib.concatStringsSep "\n" (lib.mapAttrsToList renderSection settings);

  # Drop-in configuration that makes gssproxy act as the in-kernel NFS server
  # GSS helper, replacing rpc.svcgssd. Mirrors examples/24-nfs-server.conf.in.
  nfsServerSettings = lib.optionalAttrs cfg.nfs.server.enable {
    "service/nfs-server" = {
      mechs = "krb5";
      socket = cfg.nfs.server.socket;
      cred_store = "keytab:${cfg.nfs.server.keytab}";
      trusted = true;
      kernel_nfsd = true;
      euid = 0;
    };
  };

  baseSettings = {
    gssproxy = lib.optionalAttrs (cfg.debugLevel != null) {
      debug_level = cfg.debugLevel;
    };
  };

  finalSettings = lib.recursiveUpdate (lib.recursiveUpdate baseSettings nfsServerSettings) cfg.settings;

  configFile = pkgs.writeText "gssproxy-nixos.conf" (settingsToConf finalSettings);
in
{
  options.services.gssproxy = {
    enable = lib.mkEnableOption "the GSSAPI proxy daemon (gssproxy)";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.gssproxy;
      defaultText = lib.literalExpression "pkgs.gssproxy";
      description = "The gssproxy package to use.";
    };

    debugLevel = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      example = 1;
      description = "Value for the global `debug_level` setting in the `[gssproxy]` section. `null` omits it.";
    };

    settings = lib.mkOption {
      type = with lib.types; attrsOf (attrsOf (oneOf [ bool int str (listOf (oneOf [ bool int str ])) ]));
      default = { };
      example = lib.literalExpression ''
        {
          "service/nfs-client" = {
            mechs = "krb5";
            cred_store = [
              "keytab:/etc/krb5.keytab"
              "ccache:FILE:/var/lib/gssproxy/clients/krb5cc_%U"
            ];
            cred_usage = "initiate";
            allow_any_uid = true;
            euid = 0;
          };
        }
      '';
      description = ''
        Free-form gssproxy configuration. The top-level attribute name is the
        section name (for example `"gssproxy"` or `"service/nfs-server"`), and
        each value is an attribute set of `key = value` entries. Boolean values
        are rendered as `yes`/`no`. A list value is emitted as one line per
        element, which is required for repeatable keys such as `cred_store`.

        These settings are deep-merged over (and therefore can override) the
        defaults generated by `services.gssproxy.nfs.server.enable`.
      '';
    };

    nfs.server = {
      enable = lib.mkEnableOption ''
        the NFS server drop-in for gssproxy. This configures gssproxy as the
        in-kernel NFSD GSS helper (replacing rpc.svcgssd), which is required to
        handle large RPCSEC/GSS credentials such as tickets carrying a
        Microsoft PAC payload (Active Directory / FreeIPA)
      '';

      keytab = lib.mkOption {
        type = lib.types.path;
        default = "/etc/krb5.keytab";
        description = "Keytab holding the `nfs/` and `host/` service keys for the NFS server.";
      };

      socket = lib.mkOption {
        type = lib.types.str;
        default = "/run/gssproxy.sock";
        description = ''
          Path of the UNIX socket the kernel uses to talk to gssproxy. This
          path is hardcoded in the kernel and should not normally be changed.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    # gssproxy always loads its main config file (PUBCONF_PATH/gssproxy.conf)
    # and fails to start if it is missing, so the generated configuration is
    # written there directly.
    environment.etc."gssproxy/gssproxy.conf".source = configFile;

    # Mask the classic kerberos NFS server helper so the kernel binds to
    # gssproxy on the first authentication request instead of rpc.svcgssd.
    systemd.services.rpc-svcgssd = lib.mkIf cfg.nfs.server.enable {
      enable = lib.mkForce false;
    };

    warnings = lib.optional cfg.nfs.server.enable ''
      services.gssproxy.nfs.server: the kernel chooses between rpc.svcgssd and
      gssproxy once, on the first GSS authentication request, and cannot switch
      afterwards. If kerberized NFS was already in use, reboot the server for
      gssproxy to take over.
    '';

    systemd.services.gssproxy = {
      description = "GSSAPI Proxy Daemon";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      before = [ "rpc-gssd.service" "nfs-server.service" "nfs-mountd.service" ];

      environment.KRB5RCACHEDIR = "/var/lib/gssproxy/rcache";

      serviceConfig = {
        Type = "notify";
        ExecStart = "${lib.getExe cfg.package} -i";
        ExecReload = "${pkgs.coreutils}/bin/kill -HUP $MAINPID";

        StateDirectory = "gssproxy gssproxy/clients gssproxy/rcache";
        StateDirectoryMode = "0700";

        # Hardening, ported from upstream systemd/gssproxy.service.in.
        ProtectSystem = "strict";
        PrivateDevices = true;
        PrivateNetwork = true;
        PrivateIPC = true;
        # Blocks access to /home which may hold ccaches, also breaks euid mappings.
        PrivateUsers = false;
        PrivateTmp = false;
        ProtectHome = false;
        ReadWritePaths = [ "/root" "/home" "/run/user" ];
        ProtectHostname = false;
        ProtectClock = true;
        # Must *not* block rw access to /proc/net/rpc/use-gss-proxy.
        ProtectKernelTunables = true;
        ProtectProc = "default";
        ProtectKernelModules = true;
        ProtectKernelLogs = true;
        ProtectControlGroups = true;
        RestrictAddressFamilies = [ "AF_UNIX" "AF_LOCAL" ];
        RestrictNamespaces = true;
        LockPersonality = true;
        MemoryDenyWriteExecute = true;
        RestrictRealtime = true;
        RestrictSUIDSGID = true;
        PrivateMounts = true;
        SystemCallFilter = [ "@system-service" ];
        SystemCallErrorNumber = "EPERM";
        SystemCallArchitectures = "native";
        NoNewPrivileges = true;
        CapabilityBoundingSet = [ "CAP_DAC_OVERRIDE" ];
        IPAddressDeny = "any";
        UMask = "0177";
      };
    };
  };
}
