//! Raw bindgen bindings for the subset of the krb5 crypto/keytab API used by
//! the credential sealing layer (see [`crate::seal`]). Generated by `build.rs`.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/krb5_bindings.rs"));
